content = open('src/autonomous.rs', 'r', encoding='utf-8').read()

old_speak = "    fn speak(&self, text: &str) {\n        if !self.config.tts_enabled { return; }\n        let safe_text = text.replace('\"', \" \").replace(\"\\n\", \" \");\n        // Edge TTS - headless MP3 generalas\n        let _ = std::process::Command::new(\"python\")\n            .args([\"-m\", \"edge_tts\", \"--voice\", \"hu-HU-NoemiNeural\", \"--text\", &safe_text, \"--write-media\", \"tts_output.mp3\"])\n            .spawn();\n        std::thread::sleep(std::time::Duration::from_millis(2000));\n        // Headless lejatszas ffplay-el (-nodisp = no window, -autoexit = kilepes utan)\n        let _ = std::process::Command::new(\"ffplay\")\n            .args([\"-nodisp\", \"-autoexit\", \"-loglevel\", \"quiet\", \"tts_output.mp3\"])\n            .spawn();\n    }"

new_speak = "    fn speak(&self, text: &str) {\n        if !self.config.tts_enabled { return; }\n        let safe_text = text.replace('\"', \" \").replace(\"\\n\", \" \");\n        let ts = std::time::SystemTime::now()\n            .duration_since(std::time::UNIX_EPOCH)\n            .unwrap_or_default()\n            .as_nanos();\n        let filename = format!(\"tts_{}.mp3\", ts);\n        // Edge TTS - headless MP3 generalas, megvárjuk\n        let gen = std::process::Command::new(\"python\")\n            .args([\"-m\", \"edge_tts\", \"--voice\", \"hu-HU-NoemiNeural\", \"--text\", &safe_text, \"--write-media\", &filename])\n            .output();\n        match gen {\n            Ok(_) => {\n                // Headless lejatszas ffplay-el, megvárjuk amíg végez\n                let _ = std::process::Command::new(\"ffplay\")\n                    .args([\"-nodisp\", \"-autoexit\", \"-loglevel\", \"quiet\", &filename])\n                    .status();\n                // Töröljük a temp fájlt\n                let _ = std::fs::remove_file(&filename);\n            }\n            Err(e) => {\n                eprintln!(\"  {} TTS error: {}\", \"ERROR:\".red(), e);\n            }\n        }\n    }"

content = content.replace(old_speak, new_speak)
open('src/autonomous.rs', 'w', encoding='utf-8').write(content)
print('OK')
