/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NapiMemoryResult {
  text: string
  depth: number
  layer: string
  distance: number
  memoryScope: string
}
export interface NapiStatusResult {
  version: string
  blocks: number
  appendLog: number
  layers: Array<string>
}
export interface NapiActionResult {
  status: string
  message: string
}
export interface NapiBuildResult {
  status: string
  message: string
  blocks: number
  depths: number
}
export interface NapiFindResult {
  text: string
  depth: number
  layer: string
}
export interface NapiLookResult {
  text: string
  depth: number
  layer: string
  distance: number
}
export declare function setConfigPath(path: string): void
export declare function getConfigPath(): string
export declare function status(): NapiStatusResult
export declare function recall(query: string, k?: number | undefined | null): Array<NapiMemoryResult>
export declare function remember(text: string, layer?: string | undefined | null, importance?: number | undefined | null): NapiActionResult
export declare function find(query: string, k?: number | undefined | null): Array<NapiFindResult>
export declare function look(x: number, y: number, z: number, zoom: number, k?: number | undefined | null): Array<NapiLookResult>
export declare function build(force?: boolean | undefined | null): NapiBuildResult
