# ════════════════════════════════════════════════════════════════════════════
# install.ps1 — Install Microscope Memory shorthand + optional PATH entry
# ════════════════════════════════════════════════════════════════════════════
#
# Usage:
#   .\scripts\install.ps1                 install 'mm' to ~\bin (or %LOCALAPPDATA%\Programs\Microscope\bin)
#   .\scripts\install.ps1 -Uninstall      remove the symlinks we created
#   .\scripts\install.ps1 -BinLink        also create a 'microscope-mem' shim
#   .\scripts\install.ps1 -Prefix 'C:\tools'   install to that dir
#   .\scripts\install.ps1 -NoEnv          skip writing env to PowerShell profile
#
# What it does:
#   1. Copies 'mm.ps1' to the chosen bin dir and creates 'mm.cmd' shim
#   2. Optionally creates a 'microscope-mem.cmd' shim to the local binary
#   3. Writes an env file with documented variables
#   4. Adds a dot-source line to $PROFILE unless -NoEnv
#
# ════════════════════════════════════════════════════════════════════════════

[CmdletBinding()]
param(
    [string]$Prefix,
    [switch]$Uninstall,
    [switch]$BinLink,
    [switch]$NoEnv
)

$ErrorActionPreference = "Stop"

# ─── Defaults ───────────────────────────────────────────────────────────────
if (-not $Prefix) {
    if ($env:LOCALAPPDATA) {
        $Prefix = Join-Path $env:LOCALAPPDATA "Programs\Microscope\bin"
    } else {
        $Prefix = Join-Path $HOME "bin"
    }
}
$ScriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Definition }
$RepoRoot  = (Resolve-Path (Join-Path $ScriptDir "..")).Path

# ─── Uninstall ──────────────────────────────────────────────────────────────
if ($Uninstall) {
    Write-Host "Uninstalling Microscope Memory shorthand..."
    foreach ($name in @("mm.cmd", "mm", "mm.ps1", "microscope-mem.cmd")) {
        $p = Join-Path $Prefix $name
        if (Test-Path $p) { Remove-Item $p -Force; Write-Host "  removed $p" }
    }
    $envFile = Join-Path $env:APPDATA "Microscope\env.ps1"
    if (Test-Path $envFile) { Remove-Item $envFile -Force; Write-Host "  removed $envFile" }
    # Remove dot-source from $PROFILE
    $profile = $PROFILE.CurrentUserAllHosts
    if ($profile -and (Test-Path $profile)) {
        $lines = Get-Content $profile
        $kept = $lines | Where-Object { $_ -notmatch "Microscope[\\/]env\.ps1" }
        if ($kept.Count -ne $lines.Count) {
            $kept | Set-Content $profile -Encoding utf8
            Write-Host "  cleaned $profile"
        }
    }
    Write-Host "Done."
    exit 0
}

# ─── Ensure prefix ──────────────────────────────────────────────────────────
if (-not (Test-Path $Prefix)) {
    try { New-Item -ItemType Directory -Path $Prefix -Force | Out-Null }
    catch { Write-Error "Cannot create $Prefix : $_"; exit 1 }
}

# ─── Copy mm and create mm.cmd shim ─────────────────────────────────────────
# The 'mm' dispatcher is a bash script (works in Git Bash / WSL / Linux / macOS).
# We copy it under its original name and create a .cmd shim that delegates to
# bash, so Windows users can also call `mm` from cmd.exe or PowerShell.
$mmPs1Src = Join-Path $ScriptDir "mm"
$mmPs1Dst = Join-Path $Prefix "mm"            # bash script (no extension)
$mmCmdDst = Join-Path $Prefix "mm.cmd"

if (-not (Test-Path $mmPs1Src)) {
    Write-Error "Source not found: $mmPs1Src"
    exit 1
}

# Copy the bash dispatcher (keep its original name so .cmd shim can find it)
Copy-Item $mmPs1Src $mmPs1Dst -Force
Write-Host "  copied $mmPs1Dst"

# Find a bash interpreter to delegate to.
# Priority: Git Bash (C:\Program Files\Git\bin\bash.exe) > WSL bash > bash on PATH.
function Find-BashExe {
    $candidates = @(
        (Join-Path $env:ProgramFiles "Git\bin\bash.exe"),
        (Join-Path $env:ProgramFiles "Git\usr\bin\bash.exe"),
        (Join-Path ${env:ProgramFiles(x86)} "Git\bin\bash.exe"),
        "C:\Windows\System32\bash.exe"   # WSL ships here on Win10+
    )
    foreach ($c in $candidates) {
        if ($c -and (Test-Path $c)) { return (Resolve-Path $c).Path }
    }
    $cmd = Get-Command bash.exe -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return $null
}
$bashExe = Find-BashExe

if ($bashExe) {
    # .cmd shim delegates to bash. Quoting: %* passes through verbatim.
    $shimContent = "@echo off`r`nREM mm.cmd - Microscope Memory shorthand shim`r`nREM Auto-generated by scripts\install.ps1 - do not edit by hand.`r`n`"$bashExe`" `"$mmPs1Dst`" %*"
    Set-Content -Path $mmCmdDst -Value $shimContent -Encoding ascii -Force
    Write-Host "  wrote $mmCmdDst (via $bashExe)"
} else {
    Write-Warning "bash.exe not found. mm.cmd shim not created. Install Git for Windows (https://git-scm.com) or enable WSL to use 'mm' from cmd."
}

# Also drop a PowerShell-native function file users can dot-source
$mmPs1Native = Join-Path $Prefix "mm.ps1"
@'
# mm.ps1 - PowerShell-native wrapper for the Microscope Memory bash shorthand.
# Dot-source this file in your $PROFILE to get an `mm` function inside PowerShell:
#   . "$env:LOCALAPPDATA\Programs\Microscope\bin\mm.ps1"
# It calls the bash dispatcher via Git Bash / WSL, so behavior is identical to `mm` on POSIX.
function mm {
    [CmdletBinding()]
    param(
        [Parameter(ValueFromRemainingArguments=$true)][string[]]$Args
    )
    $bash = (Get-Command bash.exe -ErrorAction SilentlyContinue).Source
    if (-not $bash) {
        $bash = Join-Path $env:ProgramFiles "Git\bin\bash.exe"
    }
    if (-not (Test-Path $bash)) {
        Write-Error "bash.exe not found. Install Git for Windows to use mm."
        return
    }
    $script = Join-Path (Split-Path -Parent $PSCommandPath) "mm"
    & $bash $script @Args
}
'@ | Set-Content -Path $mmPs1Native -Encoding utf8 -Force
Write-Host "  wrote $mmPs1Native (dot-source for PowerShell mm function)"

# ─── Optional: microscope-mem.cmd shim to the local binary ─────────────────
if ($BinLink) {
    $binSrc = Join-Path $RepoRoot "target\release\microscope-mem.exe"
    if (-not (Test-Path $binSrc)) {
        Write-Warning "$binSrc not found. Build first with: cargo build --release"
    } else {
        $binDst = Join-Path $Prefix "microscope-mem.cmd"
        $shim = @"
@echo off
REM microscope-mem.cmd shim — auto-generated
"$binSrc" %*
"@
        Set-Content -Path $binDst -Value $shim -Encoding ascii -Force
        Write-Host "  wrote $binDst"
    }
}

# ─── Env file ───────────────────────────────────────────────────────────────
if (-not $NoEnv) {
    $envDir  = Join-Path $env:APPDATA "Microscope"
    $envFile = Join-Path $envDir "env.ps1"
    if (-not (Test-Path $envDir)) { New-Item -ItemType Directory -Path $envDir -Force | Out-Null }

    $envContent = @"
# ════════════════════════════════════════════════════════════════════════════
# Microscope Memory — PowerShell environment configuration
# Dot-sourced automatically by `$PROFILE (added by install.ps1).
# ════════════════════════════════════════════════════════════════════════════

# Required: full path to the microscope-mem binary. The mm script will also
# auto-discover via `$env:MICROSCOPE_HOME\target\release or your `$PATH.
# `$env:MICROSCOPE_BIN = "$RepoRoot\target\release\microscope-mem.exe"

# Optional: project root
# `$env:MICROSCOPE_HOME = "$RepoRoot"

# Optional: defaults for the mm shorthand
`$env:MICROSCOPE_DEFAULT_LAYER = if (`$env:MICROSCOPE_DEFAULT_LAYER) { `$env:MICROSCOPE_DEFAULT_LAYER } else { "long_term" }
`$env:MICROSCOPE_DEFAULT_K     = if (`$env:MICROSCOPE_DEFAULT_K)     { `$env:MICROSCOPE_DEFAULT_K }     else { "3" }
`$env:MICROSCOPE_DEFAULT_IMPORT = if (`$env:MICROSCOPE_DEFAULT_IMPORT) { `$env:MICROSCOPE_DEFAULT_IMPORT } else { "5" }

# Optional: hook behaviour
# `$env:MICROSCOPE_STOP_MODE   = "transcript"   # transcript | session_file | none
# `$env:MICROSCOPE_RECALL_K    = "5"
# `$env:MICROSCOPE_QUIET       = "0"
"@
    Set-Content -Path $envFile -Value $envContent -Encoding utf8 -Force
    Write-Host "  wrote $envFile"

    # Add to PowerShell profile (idempotent)
    $profile = $PROFILE.CurrentUserAllHosts
    if ($profile) {
        $profileDir = Split-Path -Parent $profile
        if ($profileDir -and -not (Test-Path $profileDir)) {
            New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
        }
        if (-not (Test-Path $profile)) {
            # Create empty UTF-8 file (no BOM) so Add-Content below stays consistent.
            $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
            [System.IO.File]::WriteAllText($profile, "", $utf8NoBom)
        }

        $content = Get-Content $profile -Raw -ErrorAction SilentlyContinue
        if ($content -notmatch "Microscope[\\/]env\.ps1") {
            # Append with explicit UTF-8 (no BOM) to preserve profile readability.
            $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
            $line = "`n# Microscope Memory shorthand`n. '$envFile'`n"
            $stream = [System.IO.File]::Open($profile, [System.IO.FileMode]::Append, [System.IO.FileAccess]::Write)
            try {
                $bytes = $utf8NoBom.GetBytes($line)
                $stream.Write($bytes, 0, $bytes.Length)
            } finally {
                $stream.Close()
            }
            Write-Host "  appended dot-source to $profile"
        }
    }
}

# ─── PATH check ─────────────────────────────────────────────────────────────
$currentPath = $env:PATH -split ";"
if ($currentPath -notcontains $Prefix) {
    Write-Host ""
    Write-Host "Note: $Prefix is not in your PATH." -ForegroundColor Yellow
    Write-Host "Add it with:  `$env:PATH = '$Prefix;' + `$env:PATH"
    Write-Host "Or persistently:  [Environment]::SetEnvironmentVariable('PATH', '$Prefix;' + [Environment]::GetEnvironmentVariable('PATH', 'User'), 'User')"
}

Write-Host ""
Write-Host "Done. Test with:  mm h"
Write-Host "Uninstall with:  .\scripts\install.ps1 -Uninstall"
Write-Host ""
Write-Host "Optional: generate .claude/settings.json with the correct hook path:"
Write-Host "  .\scripts\install-claude-hooks.ps1"
